all:
  children:
    production:
      children:
        webservers:
          hosts:
            web01:
              ansible_host: 34.238.150.255
            web02:
              ansible_host: 54.175.75.34
        dbservers:
          hosts:
            db01:
              ansible_host: 98.80.252.112